# Generated by Django 4.2.14 on 2024-07-12 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='Услуга')),
                ('service_description', models.TextField(verbose_name='Описание услуги')),
                ('service_image', models.ImageField(upload_to='service_images/', verbose_name='Картинка услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=255, verbose_name='Опция')),
                ('options_description', models.TextField(verbose_name='Описание опции')),
                ('option_image', models.ImageField(upload_to='option_imafes/', verbose_name='Картинка опции')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='web.Service', verbose_name='Услуга')),
            ],
        ),
    ]
